# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: p2p.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tp2p.proto\x12\x03p2p\"\x12\n\x10ListFilesRequest\"-\n\x11ListFilesResponse\x12\x18\n\x05\x66iles\x18\x01 \x03(\x0b\x32\t.p2p.File\"I\n\x12RequestFileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0f\n\x07\x66ileurl\x18\x02 \x01(\t\x12\x10\n\x08username\x18\x03 \x01(\t\"\x1c\n\tFileChunk\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\")\n\x04\x46ile\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0f\n\x07\x66ileurl\x18\x02 \x01(\t\"\'\n\x13\x44iscoverFileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"-\n\x14\x44iscoverFileResponse\x12\x15\n\rpeerAddresses\x18\x01 \x01(\t\"\x15\n\x13ListAllFilesRequest\"0\n\x14ListAllFilesResponse\x12\x18\n\x05\x66iles\x18\x01 \x03(\x0b\x32\t.p2p.File2\x95\x02\n\x0b\x46ileService\x12<\n\tListFiles\x12\x15.p2p.ListFilesRequest\x1a\x16.p2p.ListFilesResponse\"\x00\x12:\n\x0bRequestFile\x12\x17.p2p.RequestFileRequest\x1a\x0e.p2p.FileChunk\"\x00\x30\x01\x12\x45\n\x0c\x44iscoverFile\x12\x18.p2p.DiscoverFileRequest\x1a\x19.p2p.DiscoverFileResponse\"\x00\x12\x45\n\x0cListAllFiles\x12\x18.p2p.ListAllFilesRequest\x1a\x19.p2p.ListAllFilesResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'p2p_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LISTFILESREQUEST']._serialized_start=18
  _globals['_LISTFILESREQUEST']._serialized_end=36
  _globals['_LISTFILESRESPONSE']._serialized_start=38
  _globals['_LISTFILESRESPONSE']._serialized_end=83
  _globals['_REQUESTFILEREQUEST']._serialized_start=85
  _globals['_REQUESTFILEREQUEST']._serialized_end=158
  _globals['_FILECHUNK']._serialized_start=160
  _globals['_FILECHUNK']._serialized_end=188
  _globals['_FILE']._serialized_start=190
  _globals['_FILE']._serialized_end=231
  _globals['_DISCOVERFILEREQUEST']._serialized_start=233
  _globals['_DISCOVERFILEREQUEST']._serialized_end=272
  _globals['_DISCOVERFILERESPONSE']._serialized_start=274
  _globals['_DISCOVERFILERESPONSE']._serialized_end=319
  _globals['_LISTALLFILESREQUEST']._serialized_start=321
  _globals['_LISTALLFILESREQUEST']._serialized_end=342
  _globals['_LISTALLFILESRESPONSE']._serialized_start=344
  _globals['_LISTALLFILESRESPONSE']._serialized_end=392
  _globals['_FILESERVICE']._serialized_start=395
  _globals['_FILESERVICE']._serialized_end=672
# @@protoc_insertion_point(module_scope)
